SQLALCHEMY_TRACK_MODIFICATIONS = False
IMAGE_DIR = 'fs'
DIR_MODE = 764
MAX_IMAGE_WIDTH = 596
MAX_IMAGE_HEIGHT = 4096
MAX_IMAGE_MOBI_LENGTH = 200
MAX_IMAGE_THUMB_LENGTH = 120
SEND_FILE_MAX_AGE_DEFAULT = 30*24*3600 #second

SECRET_KEY='dev'
SQLALCHEMY_DATABASE_URI = 'postgresql://user:password@localhost:5432/ffis'
SQLALCHEMY_ECHO = False

REDIS_MAX_404_COUNT = 3
REDIS_404_COUNT_EXPIRE = 30*60 #second